######################################################################
# Deployment
######################################################################
apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devguide-gitbook-deployment
spec:
  selector:
    matchLabels:
      app: devguide-gitbook
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: devguide-gitbook
    spec:
      containers:
      - name: devguide-gitbook
        image: beimax/devguide-gitbook:latest
        ports:
        - containerPort: 4000