[book]
title = "RefArch1.5 Documentation"
description = "RefArch1.5 Documentation"
authors = ["Pavel Bogatyrev"]

[build]
create-missing = false

[output.html]
mathjax-support = true

[output.html.playpen]
editable = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2