apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devguide-sphinx-deployment
spec:
  selector:
    matchLabels:
      app: devguide-sphinx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: devguide-sphinx
    spec:
      containers:
      - name: devguide-sphinx
        image: beimax/devguide-sphinx:latest
        ports:
        - containerPort: 80
# ===================================================================
kind: Service
apiVersion: v1
metadata:
  name: devguide-sphinx-service
spec:
  selector:
    app: devguide-sphinx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
